project: 
  type: book
  output-dir: docs
execute: 
  echo: false
book: 
  title: 用jamovi上手統計學 
  author: "原著: Danielle J. Navarro, David R. Foxcroft; 台灣正體中文翻譯:陳紹慶"
#  translator: "(台灣正體中文)"
#  date-meta: last-modified
  date-format: "YYYY MMMM D"
  doi: 10.24384/hgc3-7p15
  cover-image: images/bookcover_scaled.png
  #downloads: [pdf, epub]
  reader-mode: true
  sidebar:
    align: left
    collapse-level: 1
  page-footer:
    left: |
      <a href="https://learnstatswithjamovi.com">用jamovi上手統計學</a>
    right: |
      電子書使用 <a href="https://quarto.org/">Quarto套件</a>創建
  site-url: "https://scgeeker.github.io/lsj-book-zh_tw/"
  repo-url: "https://github.com/SCgeeker/lsj-book-zh_tw/"
  repo-actions: [edit,issue]
  sharing: [twitter, facebook]
  open-graph: true
  
  chapters: 
    - index.qmd
    - Preface.qmd
    - part: 新手須知
      chapters:
         - 01-Why-do-we-learn-statistics.qmd
         - 02-A-brief-introduction-to-research-design.qmd
    - part: jamovi初體驗
      chapters:
         - 03-Getting-started-with-jamovi.qmd
    - part: 資料處理
      chapters:
         - 04-Descriptive-statistics.qmd
         - 05-Drawing-graphs.qmd
         - 06-Pragmatic-matters.qmd
    - part: 統計理論
      chapters:
         - Prelude-Part-IV.qmd
         - 07-Introduction-to-probability.qmd
         - 08-Estimating-unknown-quantities-from-a-sample.qmd
         - 09-Hypothesis-testing.qmd
    - part: 統計方法
      chapters:
         - 10-Categorical-data-analysis.qmd
         - 11-Comparing-two-means.qmd
         - 12-Correlation-and-linear-regression.qmd
         - 13-Comparing-several-means-one-way-ANOVA.qmd
         - 14-Factorial-ANOVA.qmd
         - 15-Factor-Analysis.qmd
    - part: 貝氏統計
      chapters:
         - 16-Bayesian-statistics.qmd
    - Epilogue.qmd
    - References.qmd
  
bibliography: refs.bib
csl: apa.csl

format:
  html:
    title-block-style: none
    toc: true
    collapse: true
    html-math-method: mathjax
    include-in-header: header-includes.html
    css: styles.css
    theme:
      light: flatly
      dark: darkly
    number-sections: true
    link-external-newwindow: true
    #reference-location: margin
  epub: 
   # footnotes not rendering math in popup but ok in mainview (issue with calibre viewer)
    title: "用jamovi上手統計學 (version 0.75)"
    toc: true
    css: styles.css
    html-math-method: mathjax
    include-in-header: header-includes.html
    epub-cover-image: images/bookcover_html.png
  pdf:
    title: "用jamovi上手統計學 (version 0.75)"
    documentclass: book
    geometry:
      - paperwidth=8.00in
      - paperheight=10.00in
      - left= 1.25in
      - textwidth= 5.25in
      - top= 1.00in
      - textheight= 8.25in
      #- showframe
    include-in-header: preamble.tex
    include-before-body: first.tex
    include-after-body: backcover.tex
    toc: true
    colorlinks: true
    keep-tex: true

