# 線性模型的學習取向 {.unnumbered}

```{r}
#| include: FALSE
source("files/11_two_means.R")

```

在進入學習統計方法的各章節之前，我(譯者)想要向同學們介紹另一份由丹麥奧爾堡大學(Aalborg University)溝通與心理學系(Department of Communication and Psychology)Jonas Lindeløv教授編寫的教程**基礎統計方法的線性模型學習取向**[^V-1]。 決定翻譯本書之前，我一直有如何統整推論統計方法學習課表的苦惱。見到Lindeløv的教程，還有採用jamovi與JASP試編教材之後，發覺這是一套值得華文世界的學生及統計學教師認識的教程。其實本書原作者Dani也在 @sec-ANOVA-as-a-linear-model 提到相同的觀念，只是這個觀念在原書的章節編排，一直走到多因子變異數分析，Dani才告訴讀者。

在Lindeløv的原版教程發表後不到一年來，就由世界各地有志一同的教師翻譯成各國語言的版本，簡体中文版已由著名的網路統計知識交流學習論壇[統計之都](https://cosx.org/)的網友協作完成[^V-2]。由於簡体中文與繁體中文的統計學術語有別，而且Lindeløv的教程是以R語言為例，因此藉由翻譯這本**用jamovi上手統計學**的機會，我將原書的第五部分章節重新排列，改成如同Lindeløv教程一樣的順序，並在適當的段落，置入譯註提示讀者關於Lindeløv教程的說明及示範。在每一章屬於基礎統計方法的範例，都會附上一份包含線性模型版示範檔案。從 @sec-Correlation-and-linear-regression 到 @sec-Categorical-data-analysis 標示示範檔案的部分，我都會在增加的**譯註**置入取得線性模型版示範檔案的連結。示範檔案裡有關線性模型版示範檔案的說明，都會集中於這個章節。讀者可根據學習進度，參考譯註提示，回到這個章節取得檔案及閱讀參考說明。

## 教程前言 {-}

> 本節部分改編自[簡体中文版](https://cosx.org/2019/09/common-tests-as-linear-models/)教程前言

大部分常見的統計檢定方法（t 檢定、相關係數檢定、變異數分析（ANOVA）、卡方檢定等），本質都是線性模型的一種特例或者是非常逼近的模型。這種優雅的簡潔性意味著我們並不需要掌握太多的技巧就能學習。具體來說，所有模型的來源都是多數學生在高中時期就學過的一元一次線性模型：$y = a \cdot x + b$ 。然而，很多基礎統計課程是把各種檢定方法分開教，給學生和老師們增加了很多不必要的麻煩。在學習每一個檢定方法的基本假設時，如果不是從線性模型切入，而是每個檢定方法都死記硬背，這讓學習的複雜度倍增。因此，我認為先教線性模型，然後對線性模型的一些特殊形式更改名稱是一種優秀的教學策略，這有助於更深刻地理解假設檢定。線性模型在次數主義學派、貝氏學派和基於置換的U檢定的統計推論方法之間是互通的，對初學者而言，從線性模型開始比從認識什麼是*p*值、型I錯誤、貝氏因子或其它術語更為友好。

在入門課程教授到*無母數統計方法*的時候，可以避開**自我欺騙**的手段，直接告訴學生無母數檢定其實就是參數本質是*等級(rank)*的檢定方法。對學生來說，接受向量的概念，比相信你可以神奇地放棄各種母數統計方法所依賴的假設要好得多。實際上，在統計軟體如 JASP 裡，無母數檢定的貝氏等價模型就是使用潛在次序（Latent Rank）處理資料，而次數主義學派的無母數檢定方法用在樣本量 N > 15 的資料非常準確。

本書**統計方法**的各章節，繁體中文版保留原書的內容及單元順序，讓讀者比較傳統版與線性模型版的學習方法差別。使用本書教學的講師，可以根據個人教學經驗以及學生的回饋，採取合適的教學策略及課程規劃。有關輔助線性模型學習取向的相關資訊，教學者與學習者都可以取用Lindeløv提供的簡明整理表，英文閱讀能力不足的讀者請參考教程摘要的[簡体中文版](files/linear_tests_cheat_sheet.pdf)。

根據[教程摘要](https://www.fyears.org/tests-as-linear/linear_tests_cheat_sheet.html)，各種適用*無母數統計方法*的資料，樣本量至少要大於10，才能得到精確逼近的估計值。因此本書涉及無母數統計方法的範例，繁體中文版提供的範例資料樣本都會是至少是$N = 20$，符合樣本量條件的*無母數統計方法*示範說明及來源檔案，都會集中在這個章節。譯者開設的統計課程，採用Lindeløv教程的模式，平行教授連續變項及等級資料的統計方法，因此各章的學習順序不一定按照電子書的單元順序，請同學先看過以下各主題的對應單元提示，再進入各章閱讀及學習。

此外，許多*無母數統計方法*的線性模型版示範檔案，會創建計算變項或轉換變項，將原始資料轉換為等級資料。除了 @sec-Correlation-and-linear-regression **相關與線性迴歸**的斯皮爾曼等級相關係數範例，其他統計方法示範資料的轉換函式如下：

```
IF($source==0,0,IF($source>1,1,-1))*RANK($source)
```

<!---

（完成chapter 10~14的翻譯後，再回來整理）

## 教與學的建議 {#prelude-suggestions}

> 本節改編自簡体中文版[^V-2]

### 迴歸的基礎知識

1. 回憶高中學過的線性模型：$y = a \cdot x + b$，培養學生對斜率和截距的直覺。理解到這條公式能改寫成各種變項名稱。例如 `money = profit * time + starting_money`，或 $y = \beta_1x + \beta_2*1$，去除係數可寫成 `y ~ x + 1`。如果學生能接受的話，可以探索如何用[微分方程](https://magesblog.com/post/modelling-change)推道這些模型是，並了解 $y$ 是如何隨著 $x$ 的數值改變。
   
2. 擴展到多元迴歸模型。這部分有非常多可用的生活實例做為練習作業，讓這些概念很容易用直覺理解。加深同學如何使用這些簡潔的模型描述巨量資料集的印象。

3. 介紹如何將非數值型資料轉換為次序尺度，並進行各種練習。
   
4. 以三種前提假設規劃教學：資料的獨立性，殘差分佈的常態性，以及集中量數平方差的同質性（homoscedasticity）。
    
5. 參數的信賴（confidence）與可信（credible）區間。說明為何很難計算極大似然估計值（Maximum-Likelihood estimate），因此區間估計更為重要。
    
6. 對以上簡單的迴歸模型，簡要地認識 $R^2$。順便提及一下，這就是 [Pearson 和 Spearman 相關係數](#correlation)。

### 特殊情況 1：一個或兩個平均值（t 檢定、Wilcoxon 檢定、Mann-Whitney 檢定）

1. **單一平均值**：當只有一個變項 x 的時候，迴歸模型簡化為 $y = b$。如果 $y$ 不是連續變項，可以轉換為等比尺度。應用模型假設（只有一個 $x$，因此這些檢定方法不適用平方差的同質性）。順便提及一下，這些僅有截距的模型又名為*單一樣本 t 檢定*和 *Wilcoxon 符號次序檢定*。
    
2. **分組平均值**：如果我們把兩個變項放在 x 軸，兩者平均值的差異就是斜率。這樣就能用如同瑞士刀的線性模型來解決！應用模型的假設條件，檢查兩組平均值的平方差是否相等，相等即符合平方差的同質性。如此就能稱這個模型為**獨立 t 檢定**。試著創造一些虛擬資料，做一些練習，也許還能加上 Welch 檢定，再加上次序轉換，就能變成 Mann-Whitney U 檢定。
    
3. **相依樣本**：這種模型違反了獨立性假設。通過計算配對組的資料差異值，模型就會與 $y = b$ 等價，儘管這些方法另有專有名詞：**相依 t 檢定**和 **Wilcoxon 配對組檢定**。

### 特殊情況 2：三個或多個均值（方差分析（ANOVA））

1. **對類別轉化後的[示性變量](#dummy)：**類別的每一個取值範圍對應的迴歸係數，是如何通過乘以一個二元（binary）示性變量，來對每個取值範圍對應的截距來進行建模的。（How one regression coefficient for each level of a factor models an intercept for each level when multiplied by a binary indicator.）這只是我們為了使資料能用線性模型建模，而擴展了在 2.1 所做的事情而已。
    
2. **一個變量的均值：**[單因素方差分析（one-way ANOVA）](#anova1).
    
3. **兩個變量的均值：**[雙因素方差分析（two-way ANOVA）](#anova2).

### 特殊情況 3：三個或多個比率（卡方檢驗）

1. **對數變換：**通過對數變換，把“多元乘法”模型轉化成線性模型，從而可以對比率進行建模。關於對數線性模型和對比率的卡方檢驗的等價性，可以查閱這個非常優秀的介紹。此外，還需要介紹 (log-) odds ratio（一般翻譯為“比值比”或“優勢比”）。當“多元乘法”模型使用對數變換轉化為“加法”模型之後，我們僅加上來自 3.1 的示性變量技巧，就會在接下來發現模型等價於 3.2 和 3.3 的方差分析----除了係數的解釋發生了變化。

2. 單變量的比率：擬合優度檢驗.

3. 雙變量的比率：列聯表.

### 假設檢定

1. **視為模型比較的假設檢定：**假設檢驗用於全模型和某個參數固定了（通常為 0，也即從模型中去除）的模型進行比較，而不是對模型進行估計。比如說，在 [t 檢驗](#t2) 把兩個均值之一固定為零之後，我們探究單獨一個均值（[單樣本 t 檢驗](#t1)）對兩個組的數據的解釋程度。如果解釋程度比較好，那麼我們更傾向於這個單均值模型，而不是雙均值模型，因為前者更為簡單。假設檢驗其實是比較多個線性模型，來獲得更多的定量描述。單參數的檢驗，假設檢驗包含的信息更少。但是，同時對多個參數（如方差分析的類別變量）進行檢驗的話，模型比較就會變得沒有價值了。

2. **似然比：**似然比是一把瑞士軍刀，它適用於單樣本 t 檢驗到 GLMM 等情況。BIC 對模型複雜度進行懲罰。還有，加上先驗（prior）的話，你就能得到貝葉斯因子（Bayes Factor）。一個工具，就能解決所有問題。我在上文方差分析中使用了似然比檢驗。

--->

## 基礎統計方法線型模型示範說明  {-}

### 相關與線性迴歸 {-}

<!---我們運用 @fig-fig10-7 的虛構資料製作[資料檔案](files/10-correlatin-rank.omv)，示範等級資料的相關與迴歸分析。--->
**相關與線性迴歸**的對應單元有 @sec-what-is-correlation , @sec-the-scatter-plot , @sec-what-is-linear-model , @sec-the-regression-coefficients-parameters , @sec-regression-model-fittedness, @sec-regression-estimations , 以及 @sec-regression-assumptions 。使用等級資料計算斯皮爾曼等級相關與迴歸分析，總樣本量N必須大於10，才能得到精確逼近的估計值。譯者開設的課程使用另一套教程"General Analyses for the Linear Model in Jamovi"開發的[範例資料](https://gamlj.github.io/mixed_example1.html)進行教學，教學錄影請見這七部影片：[Part 1](https://youtu.be/aQEhIdk3rUU), [Part 2](https://youtu.be/wJXacmvoSUA), [Part 3](https://youtu.be/ZTmXS5lq93w), [Part 4](https://youtu.be/Aiu-X2kkRUs), [Part 5](https://youtu.be/cnbXIYJst9c),[Part 6](https://youtu.be/btDRX-Q-mq8), [Part 7](https://youtu.be/KupYlJoKMKU)。

<!---此外，jamovi迴歸模組無法直接處理等級資料，必須用計算變數。因此[資料檔案](omv_files_for_screenshorts/10-correlatin-rank.omv)以R程式碼示範。--->如果同學有機會處理真正的等級資料，也可以選擇使用R或其他統計軟體如JASP進行連續變項或等級資料的迴歸分析。

#### 泛統計方法的適用條件

所有基礎統計方法幾乎共享相同的適用條件(assumptions)，包括每個資料數值的獨立性(independence of data points)，殘差的常態性(normality of residuals)，以及變異同質性(homoscedasticity)。線性迴歸模性可看到些條件以及檢核方法，透過迴歸模型認識其他統計方法，就能自然知道要符合那些條件，統計分析才有意義。**需要讀者了解的用語問題**，許多中文統計書會用**假設**而非**適用條件**，用了幾次jamovi，讀者應該發現許多模組有*assumption check*的選項，其實是提供該分析是否符合適用條件的檢測。

#### 以線性模型解讀自由度

這本**用jamovi上手統計學**有一個[專門的小節](https://scgeeker.github.io/lsj-book-zh_tw/13-Factorial-ANOVA.html#%E8%87%AA%E7%94%B1%E5%BA%A6%E5%B0%B1%E6%98%AF%E8%A8%88%E7%AE%97%E6%9C%89%E5%A4%9A%E5%B0%91%E5%8F%83%E6%95%B8)，解釋什麼是自由度(degress of freedom)。不過這個小節在更動順序後，落在比較後面的 @sec-Factorial-ANOVA 。做為補充章節，剛好在此為讀者提供一點小小的說明。由於剛好重新學習線性模型與線性代數的知識，我參考翻譯本書時在閱讀的另一本中文教科書：黃志勝先生撰寫的「[機器學習的統計基礎 : 深度學習背後的核心技術](https://www.tenlong.com.tw/products/9789863126744)」，其中第4章講自由度的這一節，黃先生給的定義是「包含N個變數的線性模型中，不受限制的變數個數」(該書沒有這一句話，是我重新消化組織的)，我們能透過以下範例來逐漸認識。

1. 簡單迴歸式 $y = a + bx$。$y$與$x$都是變數，要使等號左右兩邊的數值相等，必須限制其中一個變數等於固定的數值，因此自由度$df = n - k = 2 - 1 = 1$。

2. 多元迴歸式 $y = a + b_1 x_1 +b_2 x_2$。這個等式有三個變數，要使等號左右兩邊的數值相等，同樣必須限制其中一個變數等於固定的數值，因此自由度$df = n - k = 3 - 1 = 2$。

3. 我們知道樣本平均值($\bar{X}$)是母群平均值($\mu$)的最佳估計值，公式是$\bar{X} = \frac{X_1 + X_2 + \dots + X_n}{n}$，其中有n個變數，每個變數都是隨機值且彼此獨立，沒有任何一個變數要受到限制，因此自由度$df = n - k = n - 0 = n$。

4. 樣本變異數($S^2$)是母群平均值($\sigma^2$)的最佳估計值，公式是$S^2 = \frac{\sum_{n=1}^{n}(X_i - \bar{X})^2}{n-1}$。這個公式也有同樣的n個隨機且彼此獨立的變數，但是公式中的平均值$\bar{X}$來自樣本平均值公式，所以可知$X_n = n\bar{X} - X_1 - X_2 - \dots - X_{n-1}$，也就是說$X_n$是受限制的變數，因此樣本變異數的自由度$df = n - k = n - 1$。

### 單一樣本及相依樣本 {-}

**單一樣本及相依樣本**的對應單元有 @sec-The-one-sample-t-test , @sec-the-paired-t-test , @sec-the-one-tail-t-test , @sec-t-test-effect-size , @sec-Checking-the-normality-of-a-sample , @sec-nonparameter-rank-test 。使用等級資料進行無母數統計分析，最小樣本量必須多於14，如果是採用線性模型教程，建議不要使用 @sec-nonparameter-rank-test 的範例，將連續資料的範例轉換為等級資料即可。讀者可使用線性模型版的jamovi示範檔案：[單一樣本t檢定](omv_files_for_screenshots/11_onesample_t_lm.omv)、[相依樣本t檢定](omv_files_for_screenshots/11_pairedsample_t_lm.omv)，搭配課程錄影學習~ [影片1](https://youtu.be/RxRe4Fjy4Vw)、[影片2](https://youtu.be/LtXFHi3iQEs)、[影片3](https://youtu.be/Yn0aMCdwccs)、[影片4](https://youtu.be/Usn802NSv4E)、[影片5](https://youtu.be/0JH6uQHqW-4)、[影片6]()、[影片7](https://youtu.be/Hl6iuGnN6aA)、[影片8](https://youtu.be/x6Jnn4NNC_k)。

### 比較兩組平均值 {-}

**比較兩組平均值**的對應單元有 @sec-the-independent-samples-t-test-student-test, @sec-the-independent-samples-t-test-welch-test, @sec-the-one-tail-t-test , @sec-t-test-effect-size , @sec-Checking-the-normality-of-a-sample , @sec-nonparameter-rank-test。使用等級資料進行無母數統計分析，最小樣本量必須多於10，如果是採用線性模型教程，建議不要使用 @sec-nonparameter-rank-test 的範例，將連續資料的範例轉換為等級資料即可。

Welch's t檢定是無法使用jamovi展示線性模型示範的統計方法，但是近年採用獨立組設計的心理學研究，被呼籲使用Welch's t檢定的建議越來越多，因為獨立組設計的行為科學資料經常違反變異數同質性的適用條件。在此使用R套件，展示使用線性模型輸出 @sec-the-independent-samples-t-test-welch-test 的範例。

**R程式碼**

```
df <- read_csv("files/Harpo.csv")

summary(nlme::gls(grade ~ 1 + as.factor(tutor), weights = nlme::varIdent(form=~1|tutor), method="ML", data=df))
```

**輸出結果**

```
Generalized least squares fit by maximum likelihood
  Model: grade ~ 1 + as.factor(tutor)

Coefficients:
                              Value Std.Error  t-value p-value
(Intercept)                74.53333  2.316009 32.18179  0.0000
as.factor(tutor)Bernadette -5.47778  2.688237 -2.03768  0.0502
```

讀者可使用線性模型版的jamovi示範檔案：[獨立樣本t檢定](omv_files_for_screenshots/11_independent_t_lm.omv)，搭配課程錄影學習 ~ [影片1](https://youtu.be/vENnMa3emTI)、[影片2](https://youtu.be/be3t8ajxwLs)


### 單因子變異數分析 {-}

@sec-Comparing-several-means-one-way-ANOVA **單因子變異數分析** 介紹的統計方法有單因子獨立樣本變異數分析，以及單因子重覆量數變異數分析。根據線性模型教程，譯者將這兩個兩個統計方法的示範，改編為以線性迴歸模型實作的[獨立樣本示範檔案](omv_files_for_screenshots/12-oneway-independent-ANOVA.omv)，以及[重覆量數示範檔案](omv_files_for_screenshots/12-oneway-repeated-measure-ANOVA.omv)。由於Lindeløv的教程並未提供單因子重覆量數變異數的等級資料分析示範，[重覆量數示範檔案](omv_files_for_screenshots/12-oneway-repeated-measure-ANOVA.omv)只有連續變項的版本。

依線性模型教程的順序學習的讀者與學生，可以先復習 @sec-what-is-linear-model 這一節的內容。譯者的課程教學會從迴歸模型的R-squared起手，帶領學生認識兩種單因子變異數分析的程序及適用條件。


**長表單(long table)與寬表單(wide table)**

[相依樣本t檢定](omv_files_for_screenshots/11_pairedsample_t_lm.omv)處理的分析資料，也是重覆量數設計。在這份[示範檔案](omv_files_for_screenshots/11_pairedsample_t_lm.omv)裡，兩次成績列在不同的變項欄位(`grade_test1`,`grade_test2`)，這種將同一個獨變項的不同層次之依變項資料，各自列在獨立變項欄位的資料格式，稱為**寬表單(wide table)**。電子書 @sec-oneway-repeated-measure 示範單因子重覆量數變異數分析使用的資料格式，也是寬表單。

jamovi的ANOVA模組與t檢定模組，都是用來處理寬表單資料。然而線性模型版的[單因子重覆量數變異數分析示範檔案](omv_files_for_screenshots/12-oneway-repeated-measure-ANOVA.omv)，獨變項欄位只有一個(`Task`)，依變項資料也集中於一個變項欄位(`Score`)。這種資料格式稱為**長表單(long table)**，是各種資料收集平台最原始的儲存格式。請讀者比較兩種資料格式的差異，思考最適合你的資料處理與分析操作，用那一種表單格式與分析模組有最佳效益。

- 課程錄影預計於2023/5/17之後上線。

### 多因子變異數分析 {-}

對應 @sec-Factorial-ANOVA **多因子變異數分析**。讀者可以使用改編自這一章原始範例，使用線性模型執行的[二因子獨立樣本變異數分析](omv_files_for_screenshots/13-twoway-independent-ANOVA.omv)與[二因子獨立樣本共變數分析](omv_files_for_screenshots/13-ANCOVA.omv)的jamovi檔案，自行比對與原書使用變異數分析模組製作的範例，學習如何設定與解讀分析報表與適用條件。經過前三章透過線性模型學習，此章內容應該相當容易。

- 課程錄影預計於2023/5/24之後上線。


### 類別資料分析 {-}

對應 @sec-Categorical-data-analysis **類別資料分析**，這個單元介紹四種類別資料分析方法，中文版提供使用線性模型示範檔案有[卡方適合度檢定](omv_files_for_screenshots/14_goodness_of_fit.omv)、[卡方獨立性檢定](omv_files_for_screenshots/14-contigeuncy-table.omv)、[小樣本類別資料的費雪精確檢定](omv_files_for_screenshots/14_Fisher.omv)、以及[相依樣本類別資料的麥內瑪檢定](omv_files_for_screenshots/14_McNemar.omv)。讀者開啟之前，請先確定自用的jamovi已經安裝`gamlj`模組，才能檢視與編輯**[通用線性模型(Generalized Linear Model)](https://en.wikipedia.org/wiki/Generalized_linear_model)**報表及功能選單。請者可搭配課程錄影學習 ~ (預計5/31後上線)

透過線性模型路徑，這四種統計方法都要先建立統計假設**通用線性模型**($H_0$與$H_1$)，運用變異數分析或逐步迴歸比較兩種統計假設的線性模型，才是與一般統計書介紹的方法相同。然而目前jamovi的內建功能或外掛模組，都沒有比較兩套線性模型的功能設定。中文版的示範檔案只有顯示對應$H_1$的線性模型，並且統計報告裡雖然有$\chi^2$的資訊，實際上是對數似然比檢定(log-likelihood ratio test)的結果，統計數與p值雖然接近卡方檢定，但並非真正的卡方檢定。由於似然值(likelihood)是貝氏統計方法常用的指標，譯者釋出這些範例檔案有引導讀者認識貝氏統計方法的用意。此外，jamovi 2.3.21版之後，內建Frequencies模組增加`log-linear Regression`功能，讓使用者能運用**通用線性模型**處理類別資料分析。

jamovi的內建Regression模組有三種對數迴歸的功能`2 Outcomes`，`N outcomes`，以及`Ordinal Outcomes`。這三種對數迴歸是**[一般線性模型(General linear model)](https://en.wikipedia.org/wiki/General_linear_model)**，與 @sec-Correlation-and-linear-regression 到 @sec-Factorial-ANOVA 介紹的統計方法所採用的線性模型是一樣的。需要注意的是，**[一般線性模型](https://en.wikipedia.org/wiki/General_linear_model)**不同於**[通用線性模型](https://en.wikipedia.org/wiki/Generalized_linear_model)**，兩者主要差異在於**一般線性模型**的依變項資料殘差分佈必須符合或逼近常態分佈，不過**通用線性模型**的依變項資料殘差分佈可以符合或逼近任何分析者指定的機率分佈[^V-3]。有興趣了解細節的讀者，可以點選連結開啟維基百科頁面。使用**通用線性模型**示範的四種類別資料分析方法，請見[導讀影片](https://youtu.be/XMqlLb2qNDs)。

使用通用線性模型操作[卡方適合度檢定](omv_files_for_screenshots/14_goodness_of_fit.omv)、[卡方獨立性檢定](omv_files_for_screenshots/14-contigeuncy-table.omv)、以及[相依樣本類別資料的麥內瑪檢定](omv_files_for_screenshots/14_McNemar.omv)，都要先轉換資料格式，轉換方法與過程請見[導讀影片](https://youtu.be/5SETnRPW_h4)。


------------------------------------------------------------------------


[^V-1]: [https://lindeloev.github.io/tests-as-linear/](https://lindeloev.github.io/tests-as-linear/)

[^V-2]: [https://cosx.org/2019/09/common-tests-as-linear-models/](https://cosx.org/2019/09/common-tests-as-linear-models/)

[^V-3]: 這是許多貝氏統計教材會先介紹通用線性模型的主要原因，因為事前機率與事後機率的機率分佈不需要是一樣的。
